pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        TF_CLI_ARGS            = "-no-color"
        JMETER_HOME            = "/opt/jmeter"  
        REPORT_DIR             = "jmeter-report"
    }

    parameters {
        booleanParam(name: 'APPLY', defaultValue: true, description: 'Apply Terraform changes')
        booleanParam(name: 'DESTROY', defaultValue: false, description: 'Destroy Terraform-managed resources')
        booleanParam(name: 'RUN_LOAD_TEST', defaultValue: false, description: 'Run Load Test after deployment')
    }

    stages {

        stage('Terraform Init & Plan') {
            when {
                expression { return params.APPLY == true && params.DESTROY == true }
            }
            steps {
                sh '''
                  cd terraform
                  terraform init
                  terraform plan -out=tfplan
                '''
            }
        }

        stage('Terraform Apply') {
            when {
                expression { return params.APPLY == true }
            }
            steps {
                sh '''
                  cd terraform
                  terraform apply --auto-approve tfplan
                '''
            }
        }

        stage('Load Test with k6') {
            when {
                expression { return params.RUN_LOAD_TEST == true }
            }
    steps {
        sh """
        k6 run tests/test.js
        """
    }
}


        stage('Terraform Destroy') {
            when {
                expression { return params.DESTROY == true }
            }
            steps {
                sh '''
                  cd terraform
                  terraform destroy --auto-approve
                '''
            }
        }
    }
}
