pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_SESSION_TOKEN     = credentials('aws-session-token')
    }

    stages {
        stage('Terraform Init') {
            steps {
                echo $AWS_ACCESS_KEY_ID
                echo $AWS_SECRET_ACCESS_KEY
                echo $AWS_SESSION_TOKEN
            }
        }
    }
}
